
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS background_type TEXT NOT NULL DEFAULT 'image',
  ADD COLUMN IF NOT EXISTS music_url TEXT,
  ADD COLUMN IF NOT EXISTS cursor_url TEXT,
  ADD COLUMN IF NOT EXISTS font_url TEXT,
  ADD COLUMN IF NOT EXISTS font_family TEXT,
  ADD COLUMN IF NOT EXISTS effect TEXT NOT NULL DEFAULT 'none',
  ADD COLUMN IF NOT EXISTS card_opacity NUMERIC NOT NULL DEFAULT 0.5,
  ADD COLUMN IF NOT EXISTS intro_enabled BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS intro_text TEXT DEFAULT 'click to enter',
  ADD COLUMN IF NOT EXISTS views INT NOT NULL DEFAULT 0;
